services:
    mtt_checkout.basket_identifier_service:
        class: Lenius\Basket\Identifier\Cookie

    mtt_checkout.basket_storage_service:
        class: Mtt\CheckoutBundle\Model\Basket\Storage\Session

    mtt_checkout.basket_service:
        class:  Mtt\CheckoutBundle\Service\BasketService
        arguments:
            - '@mtt_checkout.basket_storage_service'
            - '@mtt_checkout.basket_identifier_service'

    mtt_checkout.checkout_controller_service:
        class: Mtt\CheckoutBundle\Controller\CheckoutController
        tags: ['controller.service_arguments']
        arguments:
            - '@mtt_checkout.checkout_service'
            - '@mtt_catalog.product_repository.service'

    mtt_checkout.basket_service:
        class:  Mtt\CheckoutBundle\Form\OnePageCheckoutFormBuilderService
        arguments:
            - '@mtt_checkout.basket_service'