services:
    mtt_checkout.basket_identifier_service:
        class: Lenius\Basket\Identifier\Cookie

    mtt_checkout.basket_storage_service:
        class: Mtt\CheckoutBundle\Model\Storage\Session
        arguments:
            - '@session'

    mtt_checkout.basket_service:
        class:  Mtt\CheckoutBundle\Service\BasketService
        arguments:
            - '@mtt_checkout.basket_storage_service'
            - '@mtt_checkout.basket_identifier_service'
        autowire: true

    Mtt\CheckoutBundle\Service\BasketServiceInterface: '@mtt_checkout.basket_service'

    mtt_checkout.checkout_controller_action_service:
        class: Mtt\CheckoutBundle\Controller\CheckoutActionsController
        tags: ['controller.service_arguments']
        arguments:
            - '@mtt_checkout.basket_service'
            - '@mtt_catalog.product_repository.service'

